#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Usage $0 <dotfile>"
    echo ""
    echo "Render graphviz dotfile into a pdf figure"
    exit -1
fi

for INPUT in $1/*.dot; do

    OUTPUT=${INPUT/.dot/.pdf}
    TEMPEPS=`mktemp -t dot2pdf.XXXXXX` 

    dot -Teps $INPUT 2>/dev/null > $TEMPEPS
    epspdf "$TEMPEPS" $OUTPUT
    rm $TEMPEPS
done


pdfunite $1/*.pdf $1.pdf 
